### ISSUE TITLE
Branch management

### ISSUE THREAD

**Issue by TheAliRobertson** [croaljack0/IncubatePi#1]
Only one branch used for development. No separation between development code and final release. Not great project management. 

- Team 9

**Comment by 2077762b** [comment]
With only a handful of classes and no significant deviations, we found that one branch was sufficient for development. The code is yet to have a release but this will hopefully occur in the next few days once the first draft of the code is complete. Perhaps once there has been a stable release then branches could be used for making further changes. Can you be specific about what improvements could be done to the project management?

**Comment by TheAliRobertson** [comment]
The issue with the project management was just in relation to only having one branch in your repo. That's a fair reason to only have a master branch, I just thought it might be good to exercise a more developed branch management system since it is an area covered by the lectures and encouraged by the tutor. If you don't think it's necessary however, that's also fine 👍 .

**Comment by croaljack0** [comment]
First release is now pushed, as discussed. A branch project management has commenced. Closing this issue
