### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by alex-angelov** [croaljack0/IncubatePi#2]
1) How do you tune the PID constants (for different incubator sizes)?
2) Is there a general fail-safe switch? What happens if the RPi freezes while the temp gradient is high? Is there a maximum temperature restriction? 
3) More information about the expected latency between system components needed. Some RPi CPU benchmarks on parts of the code would be good to have - related to the above-mentioned issue.
Very good github project description, file management and history of commits.
-Team 11

**Comment by croaljack0** [comment]
1. The experimentation for the PID tuning is currently underway. There will only be one incubator size, a one size fits all.
2. The infant would be under human supervision, with further external monitoring systems to prevent the unlikely situation of a raspberry-pi failure causing over-heating.

Thanks for your feedback.

**Comment by croaljack0** [comment]
1. PID tuning complete, included in software directory.
2. Failsafe taken into account, discussed in previous comment.
3. Latency and response time benchmarks have been published in the Experimental Data directory, with final graphs in the GitHub README.

Everything sorted, closing this issue.
